name: Choice Test
on:
  workflow_dispatch:
    inputs:
      choice_input:
        type: choice
        options:
          - option1
          - option2
      string_input:
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Choice: ${{ github.event.inputs.choice_input }}"
          echo "String: ${{ github.event.inputs.string_input }}"
